version: "3.8"

services:
  api:
    build: ./api
    ports: ["3000:3000"]
    environment:
      - PORT=3000
      - BROWSERLESS_WS=ws://browserless:3000/?token=browserless_token
    depends_on: [browserless]

  browserless:
    build: ./browserless
    ports: ["3100:3000"]      # localhost:3100 if you want to poke it
    shm_size: 1gb             # keeps headless Chrome stable
